apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: example-rule
spec:
  groups:
  - name: example-rule
    rules:
    - alert: example-alert
      annotations:
        description: Memory on node {{ $labels.instance }} currently at {{ $value }}% 
          is under pressure
        summary: Memory usage is under pressure, system may become unstable.
      expr: |
        100 - ((node_memory_MemAvailable_bytes{job="node-exporter"} * 100) / node_memory_MemTotal_bytes{job="node-exporter"}) > 70
      for: 2m
      labels:
        severity: warning

    # - alert: NodeFilesystemAlmostOutOfSpace
    #   annotations:
    #     description: Filesystem on {{ $labels.device }} at {{ $labels.instance }}
    #       has only {{ printf "%.2f" $value }}% available space left.
    #     runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-nodefilesystemalmostoutofspace
    #     summary: Filesystem has less than 5% space left.
    #   expr: |
    #     (
    #       node_filesystem_avail_bytes{job="node-exporter",fstype!=""} / node_filesystem_size_bytes{job="node-exporter",fstype!=""} * 100 < 5
    #     and
    #       node_filesystem_readonly{job="node-exporter",fstype!=""} == 0
    #     )
    #   for: 1h
    #   labels:
    #     severity: warning